#!/usr/bin/env sh
set -eu

APPDIR="$(dirname "$(readlink -f "$0")")"
DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/taskbar-todolist-desktop"

mkdir -p "$DATA_DIR"
cd "$DATA_DIR"

exec "$APPDIR/usr/share/taskbar-todolist-desktop/taskbar-todolist-desktop" "$@"
